/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as CreateTypeRouteImport } from './routes/create.$type'
import { Route as CIdRouteImport } from './routes/c.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTypeRoute = CreateTypeRouteImport.update({
  id: '/create/$type',
  path: '/create/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$id': typeof CIdRoute
  '/create/$type': typeof CreateTypeRoute
  '/share/$id': typeof ShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$id': typeof CIdRoute
  '/create/$type': typeof CreateTypeRoute
  '/share/$id': typeof ShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$id': typeof CIdRoute
  '/create/$type': typeof CreateTypeRoute
  '/share/$id': typeof ShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$id' | '/create/$type' | '/share/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$id' | '/create/$type' | '/share/$id'
  id: '__root__' | '/' | '/c/$id' | '/create/$type' | '/share/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CIdRoute: typeof CIdRoute
  CreateTypeRoute: typeof CreateTypeRoute
  ShareIdRoute: typeof ShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$type': {
      id: '/create/$type'
      path: '/create/$type'
      fullPath: '/create/$type'
      preLoaderRoute: typeof CreateTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CIdRoute: CIdRoute,
  CreateTypeRoute: CreateTypeRoute,
  ShareIdRoute: ShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
